// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.AirportDistance
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("distanceMiles")]
        public double? DistanceMiles { get; set; }

        [JsonProperty("distanceKm")]
        public double? DistanceKm { get; set; }

        [JsonProperty("distanceNauticalMiles")]
        public double? DistanceNauticalMiles { get; set; }

        [JsonProperty("estimatedFlightTime")]
        public string EstimatedFlightTime { get; set; }

        [JsonProperty("timezoneDiffHours")]
        public long? TimezoneDiffHours { get; set; }

        [JsonProperty("bearing")]
        public long? Bearing { get; set; }

        [JsonProperty("direction")]
        public string Direction { get; set; }

        [JsonProperty("isInternational")]
        public bool? IsInternational { get; set; }

        [JsonProperty("carbonEstimateKg")]
        public long? CarbonEstimateKg { get; set; }

        [JsonProperty("airport1")]
        public Airport Airport1 { get; set; }

        [JsonProperty("airport2")]
        public Airport Airport2 { get; set; }
    }

    public partial class Airport
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("iata")]
        public string Iata { get; set; }

        [JsonProperty("icao")]
        public string Icao { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }

        [JsonProperty("state")]
        public string State { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("elevation")]
        public long? Elevation { get; set; }

        [JsonProperty("latitude")]
        public double? Latitude { get; set; }

        [JsonProperty("longitude")]
        public double? Longitude { get; set; }

        [JsonProperty("timezone")]
        public string Timezone { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
